### ISSUE TITLE
error message below on arduino 1.8.12, streaming library is up to date 

### ISSUE THREAD

**Issue by dr400** [janelia-arduino/Streaming#10]
In file included from C:\Users\**\OneDrive\Documents\Arduino\temp_\temp_.ino:5:0:

C:\Users\**\OneDrive\Documents\Arduino\libraries\Streaming\src/Streaming.h:51:10: error: redefinition of 'struct std::is_signed<_Tp>'

   struct is_signed { static const bool value = false; };

**Comment by gl1024** [comment]
I encountered the same error, while trying to build the example for ESP8266 D1 Mini from here:
https://www.hackster.io/rayburne/esp8266-webserver-using-javascript-and-xml-aa78f1

In file included from C:\Users\***\Downloads\AJAX\AJAX.ino:7:0:

C:\Users\***\Documents\Arduino\libraries\Streaming\src/Streaming.h:51:10: error: redefinition of 'struct std::is_signed<_Tp>'

   struct is_signed { static const bool value = false; };

================================

As a workaround, since type_traits exists for my build environment, I commented out the #if defined (ARDUINO)...#endif, and now it builds.

================================
I Updated line 47 in streaming.h to the following:
#if defined(ARDUINO) && !defined(ESP8266)

**Comment by peterpolidoro** [comment]
Hi. Which version of the Streaming library are you both using?

**Comment by gl1024** [comment]
Hi.  I'm using version 6.0.4.

**Comment by peterpolidoro** [comment]
I think I accidentally corrupted the version numbers and that is probably causing this error. I have bumped the latest commit to version 6.0.5. When that becomes available can you please try it and tell me if you encounter the same error? Thanks!

**Comment by gl1024** [comment]
Version 6.0.5 is working for me.  Thanks!
